# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET Core Console CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:

      matrix:

        os: [ubuntu-latest, windows-latest, macOS-latest]
               

    env:

      Solution_Name: Blazor Lab Starter Code.sln

      Test_Project_Path: testproject4.csproj
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build -c Release

      - name: Run unit tests
        run: dotnet test -c Release --logger "github;verbosity=detailed
